version: "3.8"

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./counter.js:/app/counter.js
    ports:
      - 5173:5173
